import React, { createContext, useContext, useState } from 'react'

const texts = {
  formal: {
    mode: 'formal',
    modeLabel: '존댓말',
    altModeLabel: '반말로 바꾸기',
    appSubtitle: '대화 기록과 관계·상황 설명을 바탕으로 거리두기 맥락을 분석해드립니다.',
    inputTitle: '대화 입력',
    fileTabLabel: '카카오톡 파일 (.txt)',
    smsTabLabel: '안드로이드 문자',
    fileHint: '카카오톡 대화 내보내기 파일을 올려주세요. 여러 파일을 선택할 수 있어요.',
    fileAddHint: '파일을 추가하면 대화 내용이 누적됩니다. ✕ 버튼으로 개별 파일을 제거하세요.',
    smsLabel: '문자 내용 붙여넣기',
    smsPh: 'SMS 백업 앱에서 내보낸 내용을 붙여넣어 주세요.',
    ctxLabel: '관계·상황 설명',
    ctxPh: '상대와의 관계, 지금 상황, 거리두고 싶은 이유 등을 입력해 주세요.',
    purposeTitle: '사용 목적',
    purposeHint: '현재 이 상대와 어떤 방향으로 조절하고 싶은지 선택해 주세요.',
    purposeDistanceTitle: '거리두기',
    purposeDistanceDesc: '자연스럽게 멀어지고 싶어요. 감정 소비를 줄이고 싶습니다.',
    purposeGaugeTitle: '관계 파악',
    purposeGaugeDesc: '현재 관계 거리가 궁금해요. 객관적으로 분석받고 싶습니다.',
    purposeCloserTitle: '가까워지기',
    purposeCloserDesc: '더 친해지고 싶어요. 어색함을 줄이고 연결되고 싶습니다.',
    userTitle: '사용자 설정',
    directTabLabel: '직접 입력',
    savedTabLabel: '저장 프로필',
    relTypeLabel: '관계 유형',
    relTypeSame: '동성 관계',
    relTypeOpposite: '이성 관계',
    relTypeHint: '분석 전에 반드시 선택해 주세요.',
    meLabel: '나 (발화 기준)',
    mePh: '예: 나, 민지, 태연',
    themLabel: '상대',
    themPh: '예: 길동, 미래',
    catLabel: '카테고리 이름',
    catPh: '예: 전 소개팅 상대, 직장 동료',
    btnSaveNew: '새로 저장',
    btnSaveUpdate: '정보 수정',
    btnSaveDelete: '삭제',
    btnAnalyze: '분석 시작하기',
    analyzing: '분석 중이에요…',
    analyzeSuccess: '분석이 완료되었습니다. 아래에서 결과를 확인하세요.',
    analyzeErrorRel: '관계 유형(동성 / 이성)을 선택한 후 다시 시도해 주세요.',
    analyzeErrorNames: '나와 상대를 모두 입력한 후 다시 시도해 주세요.',
    analyzeErrorData: '대화 내용이나 상황 설명을 조금 더 입력해 주세요.',
    metricsTitle: '관계 지표',
    metricsHint: '직접 조작 잠금은 슬라이더·버튼으로 바꾸는 것만 막습니다. AI 분석 반영은 AI 결과로 값이 바뀝니다.',
    lockLabel: '직접 조작 잠금',
    aiAllowLabel: 'AI 반영 허용',
    summaryTitle: '맥락 요약',
    analysisTitle: '답변 추천 · 관계 해설',
    analysisPlaceholder: '분석 시작 후 답변 추천, 관계 해설, 타이밍 제안이 여기에 표시됩니다.',
    coreTitle: '핵심 요약',
    synthesisTitle: '선택·지표 종합',
    deepTitle: '다각적 심층 분석',
    timingTitle: '답장 타이밍',
    lastThemLabel: '상대 마지막 메시지',
    relationDetailTitle: '관계 해설',
    suggestionsTitle: '답변 추천',
    closenessLabel: '가까워지는 정도',
    reasonLabel: '이유',
    selectProfile: '— 선택해 주세요 —',
    noProfile: '저장된 프로필이 없습니다.',
    profileDeleteConfirm: '선택한 프로필을 삭제하시겠습니까?',
    alertSelectProfile: '수정할 항목을 먼저 선택해 주세요.',
    alertRelType: '관계 유형(동성 / 이성)을 선택해 주세요.',
    alertCatName: '카테고리 이름을 입력해 주세요.',
    distanceLabel: '관계 거리',
    toneLabel: '분위기',
    warmth: { high: '따뜻함', mid: '중립', low: '조심스러움' },
    burdenLabel: '부담',
    instructionTitle: 'AI 추가 지시사항',
    instructionLabel: '원하는 분석 방향을 자유롭게 입력하세요',
    instructionPh: '예: 답장의 시간과 관계를 잘 생각해서 답장이랑 전략 추천해줘.',
    instructionPresets: [
      '답장의 시간과 관계를 잘 생각해서 답장이랑 전략 추천해줘.',
      '상대방의 감정을 최대한 존중하면서 자연스럽게 거리두는 전략 알려줘.',
      '가장 자연스럽고 부담 없는 답장 위주로 추천해줘.',
      '관계를 유지하면서도 내 에너지 소모를 줄일 수 있는 방법을 알려줘.',
      '상대가 나에게 어떤 감정인지 파악할 수 있는 분석에 집중해줘.',
    ],
    historyTitle: '분석 히스토리',
    historyEmpty: '저장된 분석 기록이 없습니다.',
    historyDeleteConfirm: '이 분석 기록을 삭제하시겠습니까?',
    historyPurposeLabel: '목적',
    historyMetricsLabel: '지표',
    historyReplyLabel: '추천 답장',
    historyStrategyLabel: '전략',
    historyDelete: '삭제',
    historyExpand: '펼치기',
    historyCollapse: '접기',
    historyInstructionLabel: '지시사항',
    historySelectedReply: '선택한 답장',
    historyNoInstruction: '없음',
  },
  informal: {
    mode: 'informal',
    modeLabel: '반말',
    altModeLabel: '존댓말로 바꾸기',
    appSubtitle: '대화 기록이랑 관계·상황 설명 올리면 거리두기 맥락 분석해줄게.',
    inputTitle: '대화 올리기',
    fileTabLabel: '카카오톡 파일 (.txt)',
    smsTabLabel: '안드로이드 문자',
    fileHint: '카카오톡 대화 내보내기 파일 올려봐. 여러 파일 선택해도 돼.',
    fileAddHint: '파일 추가할 때마다 대화 내용이 쌓여. ✕ 누르면 파일 빼낼 수 있어.',
    smsLabel: '문자 내용 붙여넣기',
    smsPh: 'SMS 백업 앱에서 내보낸 내용 여기다 붙여넣어봐.',
    ctxLabel: '관계·상황 설명',
    ctxPh: '상대랑 어떤 사이야? 지금 상황이랑 거리두고 싶은 이유 같은 거 써봐.',
    purposeTitle: '사용 목적',
    purposeHint: '이 상대랑 어떤 방향으로 가고 싶은지 골라봐.',
    purposeDistanceTitle: '거리두기',
    purposeDistanceDesc: '자연스럽게 멀어지고 싶어. 감정 소비 줄이고 싶어.',
    purposeGaugeTitle: '관계 파악',
    purposeGaugeDesc: '지금 관계 거리가 궁금해. 객관적으로 분석받고 싶어.',
    purposeCloserTitle: '가까워지기',
    purposeCloserDesc: '더 친해지고 싶어. 어색함 줄이고 연결되고 싶어.',
    userTitle: '사용자 설정',
    directTabLabel: '직접 입력',
    savedTabLabel: '저장 프로필',
    relTypeLabel: '관계 유형',
    relTypeSame: '동성 관계',
    relTypeOpposite: '이성 관계',
    relTypeHint: '분석 전에 꼭 골라줘.',
    meLabel: '나 (발화 기준)',
    mePh: '예: 나, 민지, 태연',
    themLabel: '상대',
    themPh: '예: 길동, 미래',
    catLabel: '카테고리 이름',
    catPh: '예: 전 소개팅 상대, 직장 동료',
    btnSaveNew: '새로 저장',
    btnSaveUpdate: '정보 수정',
    btnSaveDelete: '삭제',
    btnAnalyze: '분석 시작!',
    analyzing: '분석 중이야…',
    analyzeSuccess: '분석 완료! 아래서 결과 확인해봐.',
    analyzeErrorRel: '관계 유형(동성 / 이성) 먼저 골라줘.',
    analyzeErrorNames: '나랑 상대 이름 둘 다 입력해줘.',
    analyzeErrorData: '대화 내용이나 상황 설명 좀 더 써줘.',
    metricsTitle: '관계 지표',
    metricsHint: '직접 조작 잠금은 슬라이더·버튼으로 못 바꾸게 하는 거야. AI 반영은 분석 결과로 값이 바뀌는 거고.',
    lockLabel: '직접 조작 잠금',
    aiAllowLabel: 'AI 반영 허용',
    summaryTitle: '맥락 요약',
    analysisTitle: '답변 추천 · 관계 해설',
    analysisPlaceholder: '분석 시작하면 답변 추천, 관계 해설, 타이밍 제안 여기 나와.',
    coreTitle: '핵심 요약',
    synthesisTitle: '선택·지표 종합',
    deepTitle: '다각적 심층 분석',
    timingTitle: '답장 타이밍',
    lastThemLabel: '상대 마지막 메시지',
    relationDetailTitle: '관계 해설',
    suggestionsTitle: '답변 추천',
    closenessLabel: '가까워지는 정도',
    reasonLabel: '이유',
    selectProfile: '— 선택해봐 —',
    noProfile: '저장된 프로필이 없어.',
    profileDeleteConfirm: '이 프로필 삭제할거야?',
    alertSelectProfile: '수정할 항목 먼저 골라줘.',
    alertRelType: '관계 유형(동성 / 이성) 골라줘.',
    alertCatName: '카테고리 이름 입력해줘.',
    distanceLabel: '관계 거리',
    toneLabel: '분위기',
    warmth: { high: '따뜻해', mid: '중립', low: '조심스러워' },
    burdenLabel: '부담',
    instructionTitle: 'AI 추가 지시사항',
    instructionLabel: '원하는 분석 방향 자유롭게 입력해',
    instructionPh: '예: 답장 시간이랑 관계 잘 생각해서 답장이랑 전략 추천해줘.',
    instructionPresets: [
      '답장 시간이랑 관계 잘 생각해서 답장이랑 전략 추천해줘.',
      '상대 감정 존중하면서 자연스럽게 거리두는 전략 알려줘.',
      '제일 자연스럽고 부담 없는 답장 위주로 추천해줘.',
      '관계 유지하면서 내 에너지 소모 줄이는 방법 알려줘.',
      '상대가 나한테 어떤 감정인지 파악할 수 있는 분석에 집중해줘.',
    ],
    historyTitle: '분석 히스토리',
    historyEmpty: '저장된 분석 기록 없어.',
    historyDeleteConfirm: '이 분석 기록 삭제할거야?',
    historyPurposeLabel: '목적',
    historyMetricsLabel: '지표',
    historyReplyLabel: '추천 답장',
    historyStrategyLabel: '전략',
    historyDelete: '삭제',
    historyExpand: '펼치기',
    historyCollapse: '접기',
    historyInstructionLabel: '지시사항',
    historySelectedReply: '선택한 답장',
    historyNoInstruction: '없음',
  },
}

const SpeechContext = createContext(null)

export function SpeechProvider({ children }) {
  const [mode, setMode] = useState('formal')

  const toggle = () => setMode(m => m === 'formal' ? 'informal' : 'formal')
  const t = texts[mode]

  return (
    <SpeechContext.Provider value={{ t, mode, toggle }}>
      {children}
    </SpeechContext.Provider>
  )
}

export function useSpeech() {
  return useContext(SpeechContext)
}
